### PR TITLE
Hello rails react

### PR DESCRIPTION
**Pull request by techwolf404**
### Greetings 👋🏻
Thanks for taking the time to review my code

#### Changes Implemented
✅ Create rails react single application
✅ Create Greeting API endpoint (API/v1/message)
✅ Create a Greeting route using React
✅ Create a redux store, action, and a reducer to fetch the data from the API ('/message')

### CODE REVIEW

**Comment by sja-thedude** [comment]
Hi @techwolf404,

You have not added professional readme. Make sure to add the new readme template. If you will add in the next 5-10 mins I will proceed else invalidate it.

**Comment by sja-thedude** [comment]
Hi @techwolf404,

Make sure to add new template given [here](https://github.com/microverseinc/readme-template#readme) .

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @techwolf404, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have a professional readme. Kindly make sure to add new readme template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @techwolf404, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ All linters passing
✔️ Correct Gitflow
✔️ Professional Readme

## Required 
- [ ] Kindly make sure to create a migration file for the greetings. When the page is reloaded it should display a greeting so you should have 5 different greetings in total.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Reem-lab — APPROVED** [review]
# Hi @techwolf404, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 


## Highlights
- No Linters error ✅
- Great working on the functionality🔥🚀🎉
- Professional README ✨🚀

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
